# Generated by Django 3.2.25 on 2024-08-23 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='titlle',
            new_name='title',
        ),
    ]
